### ISSUE TITLE
sllin module does not compile with Linux kernel >= 4.11.9

### ISSUE THREAD

**Issue by knezicm** [lin-bus/linux-lin#2]
Due to the change in net_device structure in Linux kernel >= 4.11.9, sllin module does not compile ('destructor' field cannot be found). I applied a patch described in https://patchwork.kernel.org/patch/9826595/. However, now the reported errors are:

/home/pi/linux-lin/sllin/sllin.c: In function ‘sllin_kwthread’:
/home/pi/linux-lin/sllin/sllin.c:1175:2: error: unknown type name ‘sched_param’
  sched_param schparam = { .sched_priority = 40 };
  ^~~~~~~~~~~

home/pi/linux-lin/sllin/sllin.c:1175:27: error: field name not in record or union initializer
  sched_param schparam = { .sched_priority = 40 };
                           ^

/home/pi/linux-lin/sllin/sllin.c:1183:42: error: passing argument 3 of ‘sched_setscheduler’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  sched_setscheduler(current, SCHED_FIFO, &schparam);
                                          ^

**Comment by knezicm** [comment]
It seems that in recent Linux kernels (I am not sure from which version), struct sched_param has been moved from linux/sched.h to uapi/linux/sched/types.h, so that include part has to be updated in sllin.c accordingly.

Also, note that line discipline 25 is reserved for NFC NCI UART in recent kernel versions.

**Comment by knezicm** [comment]
Here is the patch for the aforementioned changes.
[recent-kernels-workaround.patch.txt](https://github.com/trainman419/linux-lin/files/1954758/recent-kernels-workaround.patch.txt)

**Comment by kbader94** [comment]
> It seems that in recent Linux kernels (I am not sure from which version), struct sched_param has been moved from linux/sched.h to uapi/linux/sched/types.h, so that include part has to be updated in sllin.c accordingly.
> 
> Also, note that line discipline 25 is reserved for NFC NCI UART in recent kernel versions.

I'm running into a problem attaching the device using the patched slcan on a newer Linux version. 
The error I get is:

ioctl TIOCSETD: Invalid argument

Is this because the LDISC 25 is reserved?
If so, what else would need to be changed? I tried changing 25 to an random value and it doesn't work. Any recommendations?

**Comment by ppisa** [comment]
The changes based on my branch and kbader94 followup work and testing for 5.10.17 kernel committed to mainline.
